apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-cleanup
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox:stable
            command:
            - date
          restartPolicy: OnFailure