# Publish an Application Internally within the Cluster Network
apiVersion: v1
kind: Service
metadata:
  name: desert-terrapin-svc
spec:
  type: ClusterIP
  selector:
    app: desert-terrapin
  ports:
  - name: web
    port: 80
    targetPort: 80