## Use a Service to Publish an Application Externally
apiVersion: v1
kind: Service
metadata:
  name: sea-turtle-svc
spec:
  type: NodePort
  selector:
    app: sea-turtle
  ports:
  - name: web
    port: 80
    targetPort: 80
    nodePort: 30080