---
- name: Get Namespace Detail
  shell: "kubectl get namespace {{ kubernetes_namespace }}"
  register: namespace_details
  ignore_errors: true

- name: Create AWX Kubernetes Project
  shell: "kubectl create namespace {{ kubernetes_namespace }}"
  when: namespace_details.rc != 0

- name: Set postgresql service name
  set_fact:
    postgresql_service_name: "{{ kubernetes_deployment_name }}-postgresql"
  when: "pg_hostname is not defined or pg_hostname == ''"

- name: Get Kubernetes API version
  command: |
    kubectl version -o json
  register: kube_version

- name: Extract server version from command output
  set_fact:
    kube_api_version: "{{ (kube_version.stdout | from_json).serverVersion.gitVersion[1:] }}"
